# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo build
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo test
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy
