# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
     environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      TEST_REPORTS: /tmp/test-reports
    
    steps:
      - checkout
      
      - run: echo build
            
      - run: |
          echo Download Dependencies
          ls -la ~
          ls -la ~/project
          mvn -v
          echo done run
          mkdir ~/.m2
          cp ~/project/settings.xml ~/.m2
          cd ~/project/notification
          mvn package
            
      - store_artifacts:
          path: notification/target/notification-1.0.0-SNAPSHOT.zip
          
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: |
          echo Running MUnit tests
          cd ~/project/notification
          mvn clean test -Dmunit.test=.*-test.*
          cp ~/project/notification/target/surefire-reports/*.xml ${TEST_REPORTS}
          cp ~/project/notification/target/surefire-reports/*.txt ${TEST_REPORTS}
      - store_artifacts:
          path: notification/target/surefire-reports
      - store_artifacts:
          path: notification/target/munit-reports
  deploy:
    steps:
      - run: |
          echo Deploy to Cloudhub
          cd ~/project/notification
          mvn package mule:deploy -DskipMunitTests
workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build
      - test
      - deploy
